apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-service
                port:
                  number: 8888