apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
spec:
  selector:
    app: wil-playground
  type: LoadBalancer
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
